### ISSUE TITLE
Seemingly incompatible with python 3

### ISSUE THREAD

**Issue by Greg-J** [m0r13/mclogalyzer#31]
```
python3 setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
creating /usr/local/lib/python3.8/dist-packages/mclogalyzer
copying build/lib/mclogalyzer/template.html -> /usr/local/lib/python3.8/dist-packages/mclogalyzer
copying build/lib/mclogalyzer/__init__.py -> /usr/local/lib/python3.8/dist-packages/mclogalyzer
copying build/lib/mclogalyzer/mclogalyzer.py -> /usr/local/lib/python3.8/dist-packages/mclogalyzer
byte-compiling /usr/local/lib/python3.8/dist-packages/mclogalyzer/__init__.py to __init__.cpython-38.pyc
byte-compiling /usr/local/lib/python3.8/dist-packages/mclogalyzer/mclogalyzer.py to mclogalyzer.cpython-38.pyc
  File "/usr/local/lib/python3.8/dist-packages/mclogalyzer/mclogalyzer.py", line 284
    print "### Warning: Unable to parse date in line=%s" % line
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("### Warning: Unable to parse date in line=%s" % line)?

running install_scripts
copying build/scripts-3.8/mclogalyzer -> /usr/local/bin
changing mode of /usr/local/bin/mclogalyzer to 775
running install_egg_info
Writing /usr/local/lib/python3.8/dist-packages/mclogalyzer-1.1.egg-info
```

I tried to process the logs anyway, but am met with:

```mclogalyzer /opt/minecraft/server/logs stats.html
Traceback (most recent call last):
  File "/usr/local/bin/mclogalyzer", line 3, in <module>
    import mclogalyzer
  File "/usr/local/lib/python3.8/dist-packages/mclogalyzer/__init__.py", line 1, in <module>
    from mclogalyzer import main
ImportError: cannot import name 'main' from partially initialized module 'mclogalyzer' (most likely due to a circular import) (/usr/local/lib/python3.8/dist-packages/mclogalyzer/__init__.py)
```

**Comment by Greg-J** [comment]
Doesn't seem to work with python2.7 either.

```mclogalyzer /opt/minecraft/server/logs stats.html
Parsing log 2021-05-12-1.log.gz (2021-05-12) ...
Traceback (most recent call last):
  File "/usr/local/bin/mclogalyzer", line 7, in <module>
    mclogalyzer.main()
  File "/usr/local/lib/python2.7/dist-packages/mclogalyzer/mclogalyzer.py", line 542, in main
    users, server, chats = parse_logs(args["logdir"], since, whitelist_users)
  File "/usr/local/lib/python2.7/dist-packages/mclogalyzer/mclogalyzer.py", line 449, in parse_logs
    if date is None or (since is not None and date < since):
UnboundLocalError: local variable 'date' referenced before assignment```
